/** Rotas da SPA — única fonte para menu e AppRouter. */
export const APP_ROUTES = {
  clientSetup: "/client-setup",
  configSetup: "/config-setup",
  login: "/login",
  dashboard: "/dashboard",
  monitoring: "/monitoring",
  realtime: "/realtime",
  integrations: "/integrations",
  integrationConsulta: (slug: string) => `/integrations/${encodeURIComponent(slug)}/consulta`,
  integrationConfig: (slug: string) => `/integrations/${encodeURIComponent(slug)}/config`,
  hubsoftAttendance: "/integrations/hubsoft/atendimentos",
  hubsoftWorkOrders: "/integrations/hubsoft/ordens-servico",
  hubsoftFinancial: "/integrations/hubsoft/financeiro",
  hubsoftDashboard: "/integrations/hubsoft/dashboard",
  hubsoftReport: "/integrations/hubsoft/relatorio",
  pops: "/pops",
  devices: "/devices",
  commercial: "/commercial",
  connections: "/connections",
  alerts: "/alerts",
  map: "/map",
  topology: "/topology",
  tools: "/tools",
  olt: "/olt",
  mikrotik: "/mikrotik",
  switch: "/switch",
  bng: "/bng",
  bgp: "/bgp",
  reports: "/reports",
  settings: "/settings",
  about: "/about",
  events: "/events",
  registros: "/registros",
  fleetDashboard: "/fleet/dashboard",
  fleetVehicles: "/fleet/vehicles",
  fleetDrivers: "/fleet/drivers",
  fleetElements: "/fleet/elements",
  fleetFuelings: "/fleet/fuelings",
  fleetFuels: "/fleet/fuels",
  fleetStations: "/fleet/stations",
  fleetCostCenters: "/fleet/cost-centers",
  fleetAlerts: "/fleet/alerts",
  fleetReports: "/fleet/reports",
} as const;

/** URLs antigas / alternativas → rota actual. */
export const LEGACY_ROUTE_REDIRECTS: Record<string, string> = {
  "/database-setup": APP_ROUTES.configSetup,
  "/bng": APP_ROUTES.bng,
  "/metrics": APP_ROUTES.integrations,
  "/monitoramento": APP_ROUTES.monitoring,
  "/equipamentos": APP_ROUTES.devices,
  "/configuracoes": APP_ROUTES.settings,
  "/ferramentas": APP_ROUTES.tools,
  "/alertas": APP_ROUTES.alerts,
  "/mapa": APP_ROUTES.map,
  "/comercial": APP_ROUTES.commercial,
  "/conexoes": APP_ROUTES.connections,
  "/integracoes": APP_ROUTES.integrations,
  "/tempo-real": APP_ROUTES.realtime,
  "/eventos": APP_ROUTES.events,
  "/overview": APP_ROUTES.dashboard,
  "/sobre": APP_ROUTES.about,
};
